/* Auto-generated dataset fallback from ministers.xlsx and officals.xlsx */
window.MINISTERS_FALLBACK_DATA = [
  {
    "Rank_Order": 1,
    "Name_EN": "C. Joseph Vijay",
    "Name_TA": "சி. ஜோசப் விஜய்",
    "Age": 52,
    "Party": "TVK",
    "Constituency": "Perambur",
    "Constituency_TA": "பெரம்பூர்",
    "Designation_EN": "Chief Minister",
    "Designation_TA": "முதலமைச்சர்",
    "Portfolios_EN": "General Administration; Home; Police; Public Service; Municipal Administration",
    "Portfolios_TA": "பொது நிர்வாகம்; உள்துறை; காவல்; பொதுப் பணி; நகராட்சி நிர்வாகம்",
    "AC_Name_Match": "PERAMBUR",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/ministers/Chief%20MInister.jpg"
  },
  {
    "Rank_Order": 2,
    "Name_EN": "N. Anand",
    "Name_TA": "என். ஆனந்த்",
    "Age": 62,
    "Party": "TVK",
    "Constituency": "T Nagar",
    "Constituency_TA": "தி நகர்",
    "Designation_EN": "Minister for Rural Development",
    "Designation_TA": "ஊரக வளர்ச்சித் துறை அமைச்சர்",
    "Portfolios_EN": "Rural Development; Panchayats; Irrigation Projects",
    "Portfolios_TA": "ஊரக வளர்ச்சி; ஊராட்சிகள்; நீர்ப்பாசனத் திட்டங்கள்",
    "AC_Name_Match": "T NAGAR",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-024_Thiyagarayanagar/ANAND_N_TN_AC_004BBBF5.webp"
  },
  {
    "Rank_Order": 3,
    "Name_EN": "Aadhav Arjuna",
    "Name_TA": "ஆதவ் அர்ஜுனா",
    "Age": 43,
    "Party": "TVK",
    "Constituency": "Villivakkam",
    "Constituency_TA": "விழிவாக்கம்",
    "Designation_EN": "Minister for Public Works & Sports",
    "Designation_TA": "பொதுப்பணி & விளையாட்டுத் துறை அமைச்சர்",
    "Portfolios_EN": "Public Works (PWD); Buildings, Highways & Ports; Sports",
    "Portfolios_TA": "பொதுப்பணி (PWD); கட்டிடங்கள், நெடுஞ்சாலைகள் & துறைமுகங்கள்; விளையாட்டு",
    "AC_Name_Match": "VILLIVAKKAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-014_Villivakkam/AADHAV_ARJUNA_TN_AC_33383CD2.webp"
  },
  {
    "Rank_Order": 4,
    "Name_EN": "K. G. Arunraj",
    "Name_TA": "கே. ஜி. அருண்ராஜ்",
    "Age": 46,
    "Party": "TVK",
    "Constituency": "Tiruchengodu",
    "Constituency_TA": "திருச்செங்கோடு",
    "Designation_EN": "Minister for Health & Family Welfare",
    "Designation_TA": "மக்கள் நல்வாழ்வுத் துறை அமைச்சர்",
    "Portfolios_EN": "Health; Medical Education; Family Welfare",
    "Portfolios_TA": "சுகாதாரம்; மருத்துவக் கல்வி; குடும்ப நலன்",
    "AC_Name_Match": "TIRUCHENGODU",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-096_Tiruchengodu/ARUNRAJ_K_G_TN_AC_2F67E1AD.webp"
  },
  {
    "Rank_Order": 5,
    "Name_EN": "K. A. Sengottaiyan",
    "Name_TA": "கே. ஏ. செங்கோட்டையன்",
    "Age": 78,
    "Party": "TVK",
    "Constituency": "Gobichettipalayam",
    "Constituency_TA": "கோபிசெட்டிபாளையம்",
    "Designation_EN": "Minister for Revenue",
    "Designation_TA": "வருவாய்த் துறை அமைச்சர்",
    "Portfolios_EN": "Revenue; Disaster Management; Legislative Assembly",
    "Portfolios_TA": "வருவாய்; பேரிடர் மேலாண்மை; சட்டமன்றம்",
    "AC_Name_Match": "GOBICHETTIPALAYAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-106_Gobichettipalayam/SENGOTTAIYAN_K_A_TN_AC_104B8FDE.webp"
  },
  {
    "Rank_Order": 6,
    "Name_EN": "P. Venkataramanan",
    "Name_TA": "பி. வெங்கடரமணன்",
    "Age": 48,
    "Party": "TVK",
    "Constituency": "Mylapore",
    "Constituency_TA": "மயிலாப்பூர்",
    "Designation_EN": "Minister for Food & Consumer Protection",
    "Designation_TA": "உணவு & நுகர்வோர் பாதுகாப்புத் துறை அமைச்சர்",
    "Portfolios_EN": "Food & Civil Supplies; Consumer Protection; Price Control",
    "Portfolios_TA": "உணவு & நுகர்வோர் பாதுகாப்பு; விலைக்கட்டுப்பாடு",
    "AC_Name_Match": "MYLAPORE",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-025_Mylapore/VENKATARAMANAN__P_TN_AC_BBE911C5.webp"
  },
  {
    "Rank_Order": 7,
    "Name_EN": "C. T. R. Nirmal Kumar",
    "Name_TA": "சி. டி. ஆர். நிர்மல் குமார்",
    "Age": 44,
    "Party": "TVK",
    "Constituency": "Thiruparankundram",
    "Constituency_TA": "திருப்பரங்குன்றம்",
    "Designation_EN": "Minister for Energy & Law",
    "Designation_TA": "மின்சாரம் & சட்டத்துறை அமைச்சர்",
    "Portfolios_EN": "Electricity; Law, Courts & Prisons; Corruption Prevention; Elections",
    "Portfolios_TA": "மின்சாரம்; சட்டம், நீதிமன்றங்கள் & சிறைகள்; ஊழல் தடுப்பு; தேர்தல்கள்",
    "AC_Name_Match": "THIRUPARANKUNDRAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-195_Thiruparankundram/NIRMALKUMAR__R__TN_AC_A772E88B.webp"
  },
  {
    "Rank_Order": 8,
    "Name_EN": "Rajmohan Arumugam",
    "Name_TA": "ராஜ்மோகம் ஆறுமுகம்",
    "Age": 39,
    "Party": "TVK",
    "Constituency": "Egmore",
    "Constituency_TA": "எழும்பூர்",
    "Designation_EN": "Minister for School Education & Tamil",
    "Designation_TA": "பள்ளி கல்வி & தமிழ் வளர்ச்சித் துறை அமைச்சர்",
    "Portfolios_EN": "School Education; Tamil Development; Culture & Information",
    "Portfolios_TA": "பள்ளி கல்வி; தமிழ் வளர்ச்சி; கலாச்சாரம் & செய்தி",
    "AC_Name_Match": "EGMORE",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-016_Egmore/RAJMOHAN_TN_AC_4E9D1CAD.webp"
  },
  {
    "Rank_Order": 9,
    "Name_EN": "T. K. Prabhu",
    "Name_TA": "டி. கே. பிரபு",
    "Age": 41,
    "Party": "TVK",
    "Constituency": "Karaikudi",
    "Constituency_TA": "காரைக்குடி",
    "Designation_EN": "Minister for Natural Resources",
    "Designation_TA": "இயற்கை வளங்கள் துறை அமைச்சர்",
    "Portfolios_EN": "Natural Resources; Minerals & Mines",
    "Portfolios_TA": "இயற்கை வளங்கள்; தாதுக்கள் & சுரங்கங்கள்",
    "AC_Name_Match": "KARAIKUDI",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-184_Karaikudi/DR_PRABHU__TK_TN_AC_64471992.webp"
  },
  {
    "Rank_Order": 10,
    "Name_EN": "S. Keerthana",
    "Name_TA": "எஸ். கீர்த்தனா",
    "Age": 30,
    "Party": "TVK",
    "Constituency": "Sivakasi",
    "Constituency_TA": "சிவகாசி",
    "Designation_EN": "Minister for Industries",
    "Designation_TA": "தொழில்துறை அமைச்சர்",
    "Portfolios_EN": "Industries; Investment Promotion",
    "Portfolios_TA": "தொழில்கள்; முதலீட்டு ஊக்குவிப்பு",
    "AC_Name_Match": "SIVAKASI",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-205_Sivakasi/KEERTHANA_S_TN_AC_85CD398D.webp"
  },
  {
    "Rank_Order": 11,
    "Name_EN": "P. Viswanathan",
    "Name_TA": "பி. விஸ்வநாதன்",
    "Age": 61,
    "Party": "INC",
    "Constituency": "Melur",
    "Constituency_TA": "மேலூர்",
    "Designation_EN": "Minister for Higher Education",
    "Designation_TA": "உயர்கல்வித் துறை அமைச்சர்",
    "Portfolios_EN": "Higher Education; Science & Technology; Electronics",
    "Portfolios_TA": "உயர் கல்வி; அறிவியல் & தொழில்நுட்பம்; மின்னணுவியல்",
    "AC_Name_Match": "MELUR",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-188_Melur/P_VISWANATHAN_TN_AC_3AB922F6.webp"
  },
  {
    "Rank_Order": 12,
    "Name_EN": "Rajesh Kumar. S",
    "Name_TA": "ராஜேஷ் குமார். எஸ்",
    "Age": 51,
    "Party": "INC",
    "Constituency": "Killiyoor",
    "Constituency_TA": "கிள்ளியூர்",
    "Designation_EN": "Minister for Tourism",
    "Designation_TA": "சுற்றுலாத்துறை அமைச்சர்",
    "Portfolios_EN": "Tourism; Tourism Development Corporation",
    "Portfolios_TA": "சுற்றுலா; சுற்றுலா வளர்ச்சிக் கழகம்",
    "AC_Name_Match": "KILLIYOOR",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-234_Killiyoor/RAJESH_KUMAR__S_TN_AC_9E89BF09.webp"
  },
  {
    "Rank_Order": 13,
    "Name_EN": "A.M. Shahjahan",
    "Name_TA": "ஏ.எம். ஷாஜஹான்",
    "Age": 57,
    "Party": "IUML",
    "Constituency": "Papanasam",
    "Constituency_TA": "பாபநாசம்",
    "Designation_EN": "Minister for Minorities Welfare",
    "Designation_TA": "சிறுபான்மையினர் நலத்துறை அமைச்சர்",
    "Portfolios_EN": "Minorities Welfare; Wakf Board",
    "Portfolios_TA": "சிறுபான்மையினர் நலன்; வக்ஃப் வாரியம்",
    "AC_Name_Match": "PAPANASAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-172_Papanasam/A_M__SHAHJAHAN_TN_AC_D6192388.webp"
  },
  {
    "Rank_Order": 14,
    "Name_EN": "Vanni Arasu",
    "Name_TA": "வன்னி அரசு",
    "Age": 55,
    "Party": "VCK",
    "Constituency": "Tindivanam",
    "Constituency_TA": "திண்டிவனம்",
    "Designation_EN": "Minister for Social Justice",
    "Designation_TA": "சமூக நீதித் துறை அமைச்சர்",
    "Portfolios_EN": "Adi Dravidar Welfare; Hill Tribes; Social Justice",
    "Portfolios_TA": "ஆதிதிராவிடர் நலன்; மலைவாழ் பழங்குடியினர்; சமூக நீதி",
    "AC_Name_Match": "TINDIVANAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-072_Tindivanam/VANNI_ARASU_TN_AC_B2CF4BB8.webp"
  },
  {
    "Rank_Order": 15,
    "Name_EN": "Vijay Tamilan Parthiban. A",
    "Name_TA": "விஜய் தமிழன் பார்த்திபன். ஏ",
    "Age": 50,
    "Party": "TVK",
    "Constituency": "Salem South",
    "Constituency_TA": "சேலம் தெற்கு",
    "Designation_EN": "Minister for Transport",
    "Designation_TA": "போக்குவரத்துத் துறை அமைச்சர்",
    "Portfolios_EN": "Transport; Motor Vehicles Act Administration",
    "Portfolios_TA": "போக்குவரத்து; மோட்டார் வாகனச் சட்டம்",
    "AC_Name_Match": "SALEM (SOUTH)",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-090_Salem__South_/VIJAY_TAMILAN_PARTHIBAN__A_TN_AC_F73A2B28.webp"
  },
  {
    "Rank_Order": 16,
    "Name_EN": "B. Rajkumar",
    "Name_TA": "பி. ராஜ்குமார்",
    "Age": 46,
    "Party": "TVK",
    "Constituency": "Cuddalore",
    "Constituency_TA": "கடலூர்",
    "Designation_EN": "Minister for Housing",
    "Designation_TA": "வீட்டுவசதித் துறை அமைச்சர்",
    "Portfolios_EN": "Housing; Town Planning; CMDA; Urban Habitat Development",
    "Portfolios_TA": "வீட்டுவசதி; நகர அமைப்பு; சிஎம்டிஏ; நகர்ப்புற வாழ்விட மேம்பாடு",
    "AC_Name_Match": "CUDDALORE",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-155_Cuddalore/B_RAJKUMAR_TN_AC_498ADFE3.webp"
  },
  {
    "Rank_Order": 17,
    "Name_EN": "T. Velmurugan",
    "Name_TA": "தி. வேல்முருகன்",
    "Age": 54,
    "Party": "TVK",
    "Constituency": "Panruti",
    "Constituency_TA": "பனருட்டி",
    "Designation_EN": "Minister for Environment & Climate Change",
    "Designation_TA": "சுற்றுச்சூழல் & காலநிலை மாற்றத் துறை அமைச்சர்",
    "Portfolios_EN": "Environment; Pollution Control; Climate Change",
    "Portfolios_TA": "சுற்றுச்சூழல்; மாசு கட்டுப்பாடு; காலநிலை மாற்றம்",
    "AC_Name_Match": "PANRUTI",
    "Image": ""
  },
  {
    "Rank_Order": 18,
    "Name_EN": "V. Sampath Kumar",
    "Name_TA": "வி. சம்பத் குமார்",
    "Age": 47,
    "Party": "TVK",
    "Constituency": "Coimbatore North",
    "Constituency_TA": "கோயம்புத்தூர் வடக்கு",
    "Designation_EN": "Minister for Backward Classes Welfare",
    "Designation_TA": "பிற்படுத்தப்பட்டோர் நலத்துறை அமைச்சர்",
    "Portfolios_EN": "Backward Classes Welfare; Most Backward Classes Welfare; De-notified Communities Welfare",
    "Portfolios_TA": "பிற்படுத்தப்பட்டோர் நலன்; மிகவும் பிற்படுத்தப்பட்டோர் நலன்; பட்டியல் நீக்கப்பட்ட சமூக நலன்",
    "AC_Name_Match": "COIMBATORE NORTH",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-118_Coimbatore__North_/V__SAMPATHKUMAR_TN_AC_73FE8D58.webp"
  },
  {
    "Rank_Order": 19,
    "Name_EN": "M. Vijay Balaji",
    "Name_TA": "எம். விஜய் பாலாஜி",
    "Age": 39,
    "Party": "TVK",
    "Constituency": "Erode East",
    "Constituency_TA": "ஈரோடு கிழக்கு",
    "Designation_EN": "Minister for Handlooms, Textiles & Khadi",
    "Designation_TA": "கைத்தறி, ஜவுளி & கதர் துறை அமைச்சர்",
    "Portfolios_EN": "Handlooms & Textiles; Khadi & Village Industries Board",
    "Portfolios_TA": "கைத்தறி & ஜவுளி; கதர் & கிராமத் தொழில்கள் வாரியம்",
    "AC_Name_Match": "ERODE EAST",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-098_Erode__East_/M_VIJAY_BALAJI_TN_AC_F992D14A.webp"
  },
  {
    "Rank_Order": 20,
    "Name_EN": "Vignesh K",
    "Name_TA": "விக்னேஷ் கே",
    "Age": 38,
    "Party": "TVK",
    "Constituency": "Kinathukadavu",
    "Constituency_TA": "கினத்துக்கடவு",
    "Designation_EN": "Minister for Prohibition & Excise",
    "Designation_TA": "மதுவிலக்கு & ஆயத்தீர்வைத் துறை அமைச்சர்",
    "Portfolios_EN": "Prohibition & Excise",
    "Portfolios_TA": "மதுவிலக்கு & ஆயத்தீர்வை",
    "AC_Name_Match": "KINATHUKADAVU",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-122_Kinathukadavu/VIGNESH_K_TN_AC_E618E41F.webp"
  },
  {
    "Rank_Order": 21,
    "Name_EN": "Thennarasu. K",
    "Name_TA": "தென்னரசு. கே",
    "Age": 36,
    "Party": "TVK",
    "Constituency": "Sriperumbudur",
    "Constituency_TA": "ஸ்ரீபெரும்புதூர்",
    "Designation_EN": "Minister for Non-Resident Tamils Welfare",
    "Designation_TA": "வெளிநாட்டு தமிழர் நலத்துறை அமைச்சர்",
    "Portfolios_EN": "Non-Resident Tamils Welfare; Refugees & Evacuees",
    "Portfolios_TA": "வெளிநாட்டு தமிழர் நலன்; அகதிகள் & வெளியேற்றப்பட்டோர்",
    "AC_Name_Match": "SRIPERUMBUDUR",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-029_Sriperumbudur/THENNARASU_K_TN_AC_476F2079.webp"
  },
  {
    "Rank_Order": 22,
    "Name_EN": "Mohamed Farvas. J",
    "Name_TA": "முகமது ஃபர்வாஸ். ஜே",
    "Age": 31,
    "Party": "TVK",
    "Constituency": "Aranthangi",
    "Constituency_TA": "அரந்தாங்கி",
    "Designation_EN": "Minister for Labour Welfare & Skill Development",
    "Designation_TA": "தொழிலாளர் நலன் & திறன் மேம்பாட்டுத் துறை அமைச்சர்",
    "Portfolios_EN": "Labour Welfare; Population, Employment & Training; Census; Weights & Measures; Urban & Rural Employment; Bonded Labour Welfare",
    "Portfolios_TA": "தொழிலாளர் நலன்; மக்கட்தொகை, வேலைவாய்ப்பு & பயிற்சி; மக்கள் தொகை கணக்கெடுப்பு; எடை & அளவைகள்; நகர்ப்புற & கிராமப்புற வேலைவாய்ப்பு; கட்டாய உழைப்பு ஒழிப்பு",
    "AC_Name_Match": "ARANTHANGI",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-183_Arantangi/MOHAMED_FARVAS__J_TN_AC_3AF2C952.webp"
  },
  {
    "Rank_Order": 23,
    "Name_EN": "V. Gandhiraj",
    "Name_TA": "வி. காந்திராஜ்",
    "Age": 52,
    "Party": "TVK",
    "Constituency": "Arakkonam",
    "Constituency_TA": "ஆரக்கோணம்",
    "Designation_EN": "Minister for Co-operation",
    "Designation_TA": "கூட்டுறவுத் துறை அமைச்சர்",
    "Portfolios_EN": "Co-operation",
    "Portfolios_TA": "கூட்டுறவு",
    "AC_Name_Match": "ARAKKONAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-038_Arakkonam/V__GANDHIRAJ_TN_AC_73F673A2.webp"
  },
  {
    "Rank_Order": 24,
    "Name_EN": "Jegadeshwari. K",
    "Name_TA": "ஜெகதேஸ்வரி. கே",
    "Age": 40,
    "Party": "TVK",
    "Constituency": "Rajapalayam",
    "Constituency_TA": "ராஜபாளையம்",
    "Designation_EN": "Minister for Social Welfare & Women Empowerment",
    "Designation_TA": "சமூக நலன் & மகளிர் மேம்பாட்டுத் துறை அமைச்சர்",
    "Portfolios_EN": "Social Welfare including Women Welfare; Orphanages & Correctional Administration; Beggar Homes; Social Reforms & Nutritious Meal Programme",
    "Portfolios_TA": "பெண்கள் நலன் உட்பட சமூக நலன்; அனாதை இல்லங்கள் & சீர்திருத்த நிர்வாகம்; பிச்சைக்காரர் இல்லங்கள்; சமூக சீர்திருத்தம் & சத்துணவு திட்டம்",
    "AC_Name_Match": "RAJAPALAYAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-202_Rajapalayam/JEGADESHWARI__K_TN_AC_57B26851.webp"
  },
  {
    "Rank_Order": 25,
    "Name_EN": "Vinoth",
    "Name_TA": "வினோத்",
    "Age": 32,
    "Party": "TVK",
    "Constituency": "Kumbakonam",
    "Constituency_TA": "கும்பகோணம்",
    "Designation_EN": "Minister for Agriculture - Farmers Welfare",
    "Designation_TA": "வேளாண்மை - விவசாயிகள் நலத்துறை அமைச்சர்",
    "Portfolios_EN": "Agriculture; Agricultural Engineering; Agro Service Co-operatives; Horticulture; Sugar; Sugarcane Excise; Sugarcane Development; Waste Land Development",
    "Portfolios_TA": "வேளாண்மை; வேளாண் பொறியியல்; வேளாண் சேவை கூட்டுறவுகள்; தோட்டக்கலை; சர்க்கரை; கரும்பு ஆயத்தீர்வை; கரும்பு மேம்பாடு; வீண் நிலம் மேம்பாடு",
    "AC_Name_Match": "KUMBAKONAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-171_Kumbakonam/VINOTH_TN_AC_AC7FEEF4.webp"
  },
  {
    "Rank_Order": 26,
    "Name_EN": "C. Vijayalakshmi",
    "Name_TA": "சி. விஜயலட்சுமி",
    "Age": 50,
    "Party": "TVK",
    "Constituency": "Kumarapalayam",
    "Constituency_TA": "குமாரபாளையம்",
    "Designation_EN": "Minister for Milk & Dairy Development",
    "Designation_TA": "பால் & பால்வள மேம்பாட்டுத் துறை அமைச்சர்",
    "Portfolios_EN": "Milk & Dairy Development",
    "Portfolios_TA": "பால் & பால்வள மேம்பாடு",
    "AC_Name_Match": "KUMARAPALAYAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-097_Kumarapalayam/C_VIJAYALAKSHMI_TN_AC_54C0EFBF.webp"
  },
  {
    "Rank_Order": 27,
    "Name_EN": "D. Sarathkumar",
    "Name_TA": "டி. சரத்குமார்",
    "Age": 34,
    "Party": "TVK",
    "Constituency": "Tambaram",
    "Constituency_TA": "தாம்பரம்",
    "Designation_EN": "Minister for Human Resources Management",
    "Designation_TA": "மனித வளங்கள் மேலாண்மைத் துறை அமைச்சர்",
    "Portfolios_EN": "Human Resources Management; Ex-Servicemen Welfare",
    "Portfolios_TA": "மனித வளங்கள் மேலாண்மை; முன்னாள் ராணுவ வீரர்கள் நலன்",
    "AC_Name_Match": "TAMBARAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-031_Tambaram/D_SARATHKUMAR_TN_AC_8BE3F799.webp"
  },
  {
    "Rank_Order": 28,
    "Name_EN": "Ramesh",
    "Name_TA": "ரமேஷ்",
    "Age": 31,
    "Party": "TVK",
    "Constituency": "Srirangam",
    "Constituency_TA": "ஸ்ரீரங்கம்",
    "Designation_EN": "Minister for Hindu Religious & Charitable Endowments",
    "Designation_TA": "இந்து சமய அறநிலையத்துறை அமைச்சர்",
    "Portfolios_EN": "Hindu Religious & Charitable Endowments",
    "Portfolios_TA": "இந்து சமய அறநிலையங்கள்",
    "AC_Name_Match": "SRIRANGAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-139_Srirangam/RAMESH_TN_AC_CC190B86.webp"
  },
  {
    "Rank_Order": 29,
    "Name_EN": "Mathan Raja. P",
    "Name_TA": "மதன்ராஜா. பி",
    "Age": 41,
    "Party": "TVK",
    "Constituency": "Ottapidaram",
    "Constituency_TA": "ஒட்டப்பிடாரம்",
    "Designation_EN": "Minister for Micro, Small & Medium Enterprises",
    "Designation_TA": "சிறு, குறு மற்றும் நடுத்தர தொழில் துறை அமைச்சர்",
    "Portfolios_EN": "Rural Industries including Cottage Industries; Small Industries",
    "Portfolios_TA": "கிராமப்புற தொழில்கள் உட்பட குடிசைத் தொழில்கள்; சிறு தொழில்கள்",
    "AC_Name_Match": "OTTAPIDARAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-217_Ottapidaram/P__MATHANRAJA_TN_AC_F43C21AA.webp"
  },
  {
    "Rank_Order": 30,
    "Name_EN": "N. Marie Wilson",
    "Name_TA": "என். மேரி வில்சன்",
    "Age": 46,
    "Party": "TVK",
    "Constituency": "Dr. Radhakrishnan Nagar",
    "Constituency_TA": "டாக்டர் ராதாகிருஷ்ணன் நகர்",
    "Designation_EN": "Minister for Finance, Planning & Development",
    "Designation_TA": "நிதி, திட்டமிடல் & மேம்பாட்டுத் துறை அமைச்சர்",
    "Portfolios_EN": "Finance; Pensions & Pensionary Benefits; Planning & Development",
    "Portfolios_TA": "நிதி; ஓய்வூதியம் & ஓய்வூதிய நலன்கள்; திட்டமிடல் & மேம்பாடு",
    "AC_Name_Match": "DR. RADHAKRISHNAN NAGAR",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-011_Dr_Radhakrishnan_Nagar/N__MARIE_WILSON_TN_AC_454C7872.webp"
  },
  {
    "Rank_Order": 31,
    "Name_EN": "Srinath",
    "Name_TA": "ஸ்ரீநாத்",
    "Age": 52,
    "Party": "TVK",
    "Constituency": "Thoothukudi",
    "Constituency_TA": "தூத்துக்குடி",
    "Designation_EN": "Minister for Fisheries - Fishermen Welfare",
    "Designation_TA": "மீன்வளம் - மீனவர் நலத்துறை அமைச்சர்",
    "Portfolios_EN": "Fisheries; Fisheries Development Corporation",
    "Portfolios_TA": "மீன்வளம்; மீன்வள மேம்பாட்டுக் கழகம்",
    "AC_Name_Match": "THOOTHUKUDI",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-214_Thoothukkudi/SRINATH_TN_AC_C672DC59.webp"
  },
  {
    "Rank_Order": 32,
    "Name_EN": "Kamali. S",
    "Name_TA": "கமலி. எஸ்",
    "Age": 28,
    "Party": "TVK",
    "Constituency": "Avinashi",
    "Constituency_TA": "அவினாசி",
    "Designation_EN": "Minister for Animal Husbandry",
    "Designation_TA": "கால்நடை வளர்ப்புத் துறை அமைச்சர்",
    "Portfolios_EN": "Animal Husbandry",
    "Portfolios_TA": "கால்நடை வளர்ப்பு",
    "AC_Name_Match": "AVINASHI",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-112_Avanashi/KAMALI_S_TN_AC_200E61CD.webp"
  },
  {
    "Rank_Order": 33,
    "Name_EN": "Kumar. R",
    "Name_TA": "குமார். ஆர்",
    "Age": 60,
    "Party": "TVK",
    "Constituency": "Velachery",
    "Constituency_TA": "வேளச்சேரி",
    "Designation_EN": "Minister for Artificial Intelligence, IT & Digital Services",
    "Designation_TA": "செயற்கை நுண்ணறிவு, தகவல் தொழில்நுட்பம் & டிஜிட்டல் சேவைத் துறை அமைச்சர்",
    "Portfolios_EN": "Artificial Intelligence; Information Technology; Digital Services",
    "Portfolios_TA": "செயற்கை நுண்ணறிவு; தகவல் தொழில்நுட்பம்; டிஜிட்டல் சேவைகள்",
    "AC_Name_Match": "VELACHERY",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-026_Velachery/KUMAR__R_TN_AC_15201D0F.webp"
  },
  {
    "Rank_Order": 34,
    "Name_EN": "R.V. Ranjithkumar",
    "Name_TA": "ஆர்.வி. ரஞ்சித்குமார்",
    "Age": 50,
    "Party": "TVK",
    "Constituency": "Kancheepuram",
    "Constituency_TA": "காஞ்சிபுரம்",
    "Designation_EN": "Minister for Forests",
    "Designation_TA": "வனத்துறை அமைச்சர்",
    "Portfolios_EN": "Forests",
    "Portfolios_TA": "வனத்துறை",
    "AC_Name_Match": "KANCHEEPURAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-037_Kancheepuram/R_V__RANJITHKUMAR_TN_AC_A4F897B1.webp"
  },
  {
    "Rank_Order": 35,
    "Name_EN": "Logesh Tamilselvan D",
    "Name_TA": "லோகேஷ் தமிழ்செல்வன் டி",
    "Age": 42,
    "Party": "TVK",
    "Constituency": "Rasipuram",
    "Constituency_TA": "ராசிபுரம்",
    "Designation_EN": "Minister for Commercial Taxes & Registration",
    "Designation_TA": "வணிக வரிகள் & பதிவுத்துறை அமைச்சர்",
    "Portfolios_EN": "Commercial Taxes; Registration & Stamp Act; Debt Relief including Legislation on Money Lending; Chits; Registration of Companies",
    "Portfolios_TA": "வணிக வரிகள்; பதிவு & முத்திரைத் தீர்வை; கடன் நிவாரணம்; சீட்டு; நிறுவனங்கள் பதிவு",
    "AC_Name_Match": "RASIPURAM",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-092_Rasipuram/LOGESH_TAMILSELVAN_D_TN_AC_7F9FB5A9.webp"
  },
  {
    "Rank_Order": 36,
    "Name_EN": "Rajeev",
    "Name_TA": "ராஜீவ்",
    "Age": 33,
    "Party": "TVK",
    "Constituency": "Thiruvadanai",
    "Constituency_TA": "திருவடானை",
    "Designation_EN": "Minister for Environment & Climate Change",
    "Designation_TA": "சுற்றுச்சூழல் & காலநிலை மாற்றத் துறை அமைச்சர்",
    "Portfolios_EN": "Environment; Pollution Control Board; Climate Change",
    "Portfolios_TA": "சுற்றுச்சூழல்; மாசு கட்டுப்பாட்டு வாரியம்; காலநிலை மாற்றம்",
    "AC_Name_Match": "THIRUVADANAI",
    "Image": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-210_Tiruvadanai/RAJEEV_TN_AC_4566167E.webp"
  }
];
window.OFFICIALS_FALLBACK_DATA = [
  {
    "position": "Speaker of the Assembly",
    "position_ta": "சட்டப்பேரவை தலைவர்",
    "name": "J. C. D. Prabhakar",
    "name_ta": "ஜே. சி. டி. பிரபாகர்",
    "age": 73,
    "party": "TVK",
    "party_ta": "த.வெ.க.",
    "constituency": "Thousand Lights",
    "constituency_ta": "ஆயிரம் விளக்கு",
    "constituency_type": "General",
    "constituency_type_ta": "பொது",
    "took_office": "2026-05-12",
    "role_description": "Presiding officer of the Legislative Assembly; maintains order and acts as a neutral authority during debates.",
    "role_description_ta": "சட்டப்பேரவை நடவடிக்கைகளை நடத்தி, ஒழுங்கைப் பேணி, விவாதங்களில் நடுநிலையுடன் செயல்படும் தலைவர்.",
    "party_block": "Government",
    "party_block_ta": "அரசு",
    "image url": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-020_Thousand_Lights/PRABHAKAR_J_C_D_TN_AC_EDFEB291.webp"
  },
  {
    "position": "Leader of the Opposition",
    "position_ta": "எதிர்க்கட்சித் தலைவர்",
    "name": "Udhayanidhi Stalin",
    "name_ta": "உதயநிதி ஸ்டாலின்",
    "age": 48,
    "party": "DMK",
    "party_ta": "தி.மு.க.",
    "constituency": "Chepauk–Thiruvallikeni",
    "constituency_ta": "சேப்பாக்கம்–திருவல்லிக்கேணி",
    "constituency_type": "General",
    "constituency_type_ta": "பொது",
    "took_office": "2026-05-10",
    "role_description": "Official leader of the opposition in the Legislative Assembly.",
    "role_description_ta": "சட்டப்பேரவையில் எதிர்க்கட்சிக் கூட்டணியின் அதிகாரப்பூர்வ தலைவராக செயல்படுபவர்.",
    "party_block": "DMK Coalition",
    "party_block_ta": "தி.மு.க. கூட்டணி",
    "image url": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-019_Chepauk-Thiruvallikeni/UDHAYANIDHI_STALIN_TN_AC_D42E450E.webp"
  },
  {
    "position": "Deputy Speaker",
    "position_ta": "துணைச் சட்டப்பேரவை தலைவர்",
    "name": "M. Ravisankar",
    "name_ta": "மு. ரவிசங்கர்",
    "age": 41,
    "party": "TVK",
    "party_ta": "த.வெ.க.",
    "constituency": "Thuraiyur",
    "constituency_ta": "துறையூர்",
    "constituency_type": "General",
    "constituency_type_ta": "பொது",
    "took_office": "2026-05-12",
    "role_description": "Presides over the Assembly in the absence of the Speaker and assists in House proceedings.",
    "role_description_ta": "தலைவர் இல்லாதபோது அவையின் நடவடிக்கைகளை நடத்தி, சட்டப்பேரவை பணிகளில் உதவுபவர்.",
    "party_block": "Government",
    "party_block_ta": "அரசு",
    "image url": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-146_Thuraiyur/RAVISANKAR_M_TN_AC_D2E47EAF.webp"
  },
  {
    "position": "Leader of the House",
    "position_ta": "அவை முன்னவர்",
    "name": "K. A. Sengottaiyan",
    "name_ta": "கே. ஏ. செங்கோட்டையன்",
    "age": 78,
    "party": "TVK",
    "party_ta": "த.வெ.க.",
    "constituency": "Gobichettipalayam",
    "constituency_ta": "கோபிச்செட்டிபாளையம்",
    "constituency_type": "General",
    "constituency_type_ta": "பொது",
    "took_office": "2026-05-12",
    "role_description": "Leads the government's legislative business in the Assembly.",
    "role_description_ta": "அரசின் சட்டப்பேரவை அலுவல்களை ஒருங்கிணைத்து முன்னெடுத்து செல்லும் தலைவர்.",
    "party_block": "Government",
    "party_block_ta": "அரசு",
    "image url": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-106_Gobichettipalayam/SENGOTTAIYAN_K_A_TN_AC_104B8FDE.webp"
  },
  {
    "position": "Government Whip",
    "position_ta": "அரசுக் கொறடா",
    "name": "R. Sabarinathan",
    "name_ta": "ஆர். சபரிநாதன்",
    "age": 30,
    "party": "TVK",
    "party_ta": "த.வெ.க.",
    "constituency": "Virugampakkam",
    "constituency_ta": "விருகம்பாக்கம்",
    "constituency_type": "General",
    "constituency_type_ta": "பொது",
    "took_office": "2026-05-12",
    "role_description": "Ensures party discipline and coordinates voting in the Assembly.",
    "role_description_ta": "ஆளுங்கட்சி உறுப்பினர்களின் ஒழுங்கையும் வாக்கெடுப்பையும் ஒருங்கிணைப்பவர்.",
    "party_block": "Government",
    "party_block_ta": "அரசு",
    "image url": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-022_Virugambakkam/SABARINATHAN_R_TN_AC_42C9AF48.webp"
  },
  {
    "position": "Deputy Leader of the Opposition",
    "position_ta": "எதிர்க்கட்சி துணைத் தலைவர்",
    "name": "K. N. Nehru",
    "name_ta": "கே. என். நேரு",
    "age": 73,
    "party": "DMK",
    "party_ta": "தி.மு.க.",
    "constituency": "Tiruchirappalli (West)",
    "constituency_ta": "திருச்சிராப்பள்ளி (மேற்கு)",
    "constituency_type": "General",
    "constituency_type_ta": "பொது",
    "took_office": "2026-05-12",
    "role_description": "Assists the Leader of the Opposition in Assembly affairs.",
    "role_description_ta": "எதிர்க்கட்சித் தலைவருக்கு சட்டப்பேரவை நடவடிக்கைகளில் துணைபுரிபவர்.",
    "party_block": "DMK Coalition",
    "party_block_ta": "தி.மு.க. கூட்டணி",
    "image url": "https://pub-b25d504a24b04494839eefe88766f3e8.r2.dev/assets/image_candidates/tn-ac-140_Tiruchirappalli__West_/K_N_NEHRU_TN_AC_54BFDCCA.webp"
  }
];
